DELETE FROM servicehostconfigurationsrvcs;
DELETE FROM servicehost;
DELETE FROM servicehostconfiguration;
INSERT INTO servicehostconfiguration VALUES (1, 0, 0, 1);
INSERT INTO servicehostconfigurationsrvcs VALUES (1, 'BUILD');
INSERT INTO servicehostconfigurationsrvcs VALUES (1, 'TASKS');
INSERT INTO servicehostconfigurationsrvcs VALUES (1, 'WIKI');
INSERT INTO servicehostconfigurationsrvcs VALUES (1,'SCM');
INSERT INTO servicehostconfigurationsrvcs VALUES (1,'MAVEN');
INSERT INTO servicehost VALUES (1, '127.0.0.1', 1, 1, 1);